- lib/hutch/broker.rb
- lib/hutch/config.rb
On a project recently we wanted to adjust the `heartbeat` setting. This update
allows for passing in the `heartbeat` setting.
> Update config to allow for passing of heartbeat

- README.md
- lib/hutch/broker.rb
- lib/hutch/consumer.rb
- lib/hutch/worker.rb
- spec/hutch/broker_spec.rb
- spec/hutch/consumer_spec.rb
- spec/hutch/worker_spec.rb
I wanted to be able to set policies per consumer. I've also fixed a missing spec.
Cheers
> allow to pass custom arguments per consumers

- lib/hutch/consumer.rb
Added a logger method to the Consumer module to allow consumers to make use of the Hutch logger
> Added logger method to Consumer module

- README.md
- lib/hutch/broker.rb
- lib/hutch/config.rb
- Adds option to set a logger for bunny
- Moves connection params to private method
> Bunny logger

- .travis.yml
- circle.yml
> Add Ruby 2.3 to Travis build

- lib/hutch/worker.rb
Named variables, added a constant, extracted a private method.
> Extract-and-name to simplify complex method

- lib/hutch/broker.rb
- Adds an `#unbind_redundant_bindings` method to break up
the complex `#bind_queue` method.
- Adds a `#log_publication` method to break up the complex
`#publish` method.
> Reduce complexity of Hutch::Broker

- spec/hutch/logger_spec.rb
- spec/spec_helper.rb
This will truly silence all logging from Hutch::Logging.logger
> use true null logger for specs

- lib/hutch/cli.rb
- lib/hutch/config.rb
- lib/hutch/worker.rb
- spec/hutch/worker_spec.rb
Basically this pull request but without any refactoring: https://github.com/gocardless/hutch/pull/206
> allow for functions to run before main loop

- lib/hutch/config.rb
- spec/hutch/config_spec.rb
Fixes #208.
This is a reworked #209.
> Configuration support for HUTCH_ env vars

- hutch.gemspec
gem.add_development_dependency 'yard', '~> 0.8'
> Gemspec: yard

- lib/hutch/broker.rb
- lib/hutch/waiter.rb
- lib/hutch/worker.rb
- spec/hutch/broker_spec.rb
- spec/hutch/waiter_spec.rb
- spec/hutch/worker_spec.rb
Pulled loop logic out, updated it to use IO.select, and removed cruft
methods.
> extract process holding logic

- lib/hutch/waiter.rb
- spec/hutch/waiter_spec.rb
Signal QUIT is not support under Windows
> Don't try to register unsupported Signals

- README.md
This PR changes the README's status icons to SVG variants of themselves, for clarity. ✨
> README: Use the sharper SVG icons

- hutch.gemspec
[Changelog](https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md)
> Gem: bump simplecov to 0.12

- Gemfile
- Guardfile
Updated guard and guard-rspec to modern versions.
Guard has a new format for its Guardfile.
> Gem: guard and guard-rspec

- .travis.yml
This PR updates to latest MRI.
> Travis: Update to ruby-2.3.3

- .travis.yml
This PR updates rubies to latest releases.
> Travis: update rubies

- README.md
This PR edits the HTML table to make it render right.
> README: Try to repair HTML table

- README.md
> README: Remove badge for defunct service

- .travis.yml
> CI: use JRuby-9.2.7.0, 2.4.6

- Gemfile
- lib/hutch/error_handlers.rb
- lib/hutch/error_handlers/rollbar.rb
- spec/hutch/error_handlers/rollbar_spec.rb
This Pull Request adds an error handler that reports exceptions to Rollbar.
> Added error handler for Rollbar

- .travis.yml
> CI: Use latest Ruby versions

- README.md
- lib/hutch/consumer.rb
- spec/hutch/consumer_spec.rb
> Add lazy and quorum options for queues

- CHANGELOG.md
- lib/hutch/version.rb
As mentioned here: https://github.com/gocardless/hutch/pull/343#issuecomment-593357196 hopefully this helps with the release 🤞!
> Update changelog and version for release

- Gemfile
- lib/hutch/error_handlers.rb
- lib/hutch/error_handlers/bugsnag.rb
- spec/hutch/error_handlers/bugsnag_spec.rb
bugsnag homepage: https://bugsnag.com/
> Added error handler for Bugsnag

- lib/hutch/adapters/bunny.rb
- lib/hutch/adapters/march_hare.rb
- lib/hutch/broker.rb
`Bunny::Exchange` has been referenced unconditionally
> putting Exchange behind Adapter
