- lib/hutch/broker.rb
We ran into an issue where we had a lot of errors publishing messages to rabbit. We need to resend the failed messages and the content is available in the server logs, but it's in ruby's inspect format making it a huge pain to parse and resend. 
So what do you think about just logging the JSON we're sending out? It makes it much simpler to resend failed messages from logs, and you don't have to wonder about how things like dates were serialized.
> Serialize messages for logging using JSON

- README.md
- lib/hutch/broker.rb
- lib/hutch/config.rb
With the release of Bunny 1.7, the `read_timeout` and `write_timeout` are now up for configuration. This allows more fine grained control of timeout related error handling when reading and writing to RabbitMQ.
It is currently defaulted to `5` in Bunny and that is too low for some of our applications.
> Allow configuration of Bunny's read and write timeouts

- lib/hutch/config.rb
- spec/hutch/config_spec.rb
Inspired by Rails, I found myself wanting a configuration file like this:
```yaml
uri: <%= ENV['AMQP_URL'] %>
require_paths:
- raven
- consumers
```
> Support ERb in YAML config

- README.md
I found this information in `worker.rb` but not in the README, which seems to be the main place to find documentation for hutch. I thought it was important enough to belong on the front page.
> document graceful exits for hutch cli

- lib/hutch/broker.rb
- lib/hutch/config.rb
- spec/hutch/broker_spec.rb
This is a follow up to #139, I realized that the documentation I added is not actually what happens.
On master, sending a SIGINT to hutch will just run `kill` on the worker pool. It's graceful in that it's killing the threads before exiting the program, but it's not really graceful in regards to what those threads are actually doing (ie, processing message).
With this PR I am implementing the following:
When sending `SIGINT`, `SIGQUIT`, or `SIGTERM` to Hutch, it will:
It will set `working` to false in the pool, and enqueue an exception in the queue for each worker thread. Upon reception of the exception, the worker loop will end.
`#shutdown` kills the threads that were idling, but some workers were potentially already running so they won't get to the exception until their current job is …
> Implement graceful exit

- lib/hutch/config.rb
I was getting an error when trying to run the hutch cli:
```
/Users/ben/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/hutch-a99858756a67/lib/hutch/config.rb:85:
in `load_from_file': uninitialized constant Hutch::Config::ERB (NameError)
```
Explicitly requiring erb in the `Config` class file fixed it for me.
> Require erb for cli

- CHANGELOG.md
- Gemfile
- README.md
- lib/hutch.rb
- lib/hutch/broker.rb
- lib/hutch/config.rb
- lib/hutch/tracers.rb
- lib/hutch/tracers/newrelic.rb
- lib/hutch/tracers/null_tracer.rb
- lib/hutch/worker.rb
This adds a basic implementation for a pluggable message processing tracers.
Support for [NewRelic custom instrumentation](https://docs.newrelic.com/docs/agents/ruby-agent/features/ruby-custom-instrumentation) is included. It requires newrelic_rpm gem and I assume it's provided with Rails application.
Should be fairly easy expandable to other instrumentation sources as well.
> Basic support for tracing message processing

- hutch.gemspec
- lib/hutch/message.rb
- spec/hutch/message_spec.rb
Hi,
Using `symbolize: true` when loading JSON can lead to DoS since symbols are not garbage collected by ruby.
This PR replaces `MultiJSON.load(payload, symbolize_keys: true)` with `ActiveSupport::HashWithIndifferentAccess` in order to maintain backwards compatibility.
> Use HashWithIndifferentAccess instead of MultiJSON symbolize

- lib/hutch/broker.rb
Respect "amqps://" in the URI and use the default protocol ports (5672 and 5671) if no port is supplied in the URI
> URI improvements

- lib/hutch/broker.rb
- lib/hutch/config.rb
Add option to set bunny's worker pool size to allow for multithreaded consumers. Will probably want to add standard disclaimers about concurrency and databases, etc.
Related to https://github.com/gocardless/hutch/issues/141
> Add worker_pool_size option for multithreaded consumers

- .travis.yml
- hutch.gemspec
- lib/hutch.rb
- lib/hutch/adapter.rb
- lib/hutch/adapters/bunny.rb
- lib/hutch/adapters/march_hare.rb
- lib/hutch/broker.rb
- lib/hutch/worker.rb
- spec/hutch/broker_spec.rb
- spec/spec_helper.rb
Hi,
This PR ads [march_hare](https://github.com/ruby-amqp/march_hare) support. I don't consider it complete, since I didn't test all the cases. The test suite passes, and I also tested it using my application that was already using hutch. 
However, I didn't test all the options passed to `MarchHare.connect` since I don't have an app to test it. Also I'm not sure if I'm properly using the signals inside the main loop, but it seems to work. 
The only part which I'm not sure how to do is handling `ConnectionError`. When rabbitmq is stopped, or there is a network failure, it seems that MarchHare is calling the shutdown handler, not trying to reconnect.
I'm sorry if I'm missing something, this is my first contact with MarchHare internals.
> Add MarchHare support

- lib/hutch/broker.rb
- lib/hutch/config.rb
verify_peer and tls_ca_certificates
These are probably obscure enough to not need cli option support, but are very important when using self-signed certificates etc.
Verify_peer defaults to true (the same as the bunny default) and tls_ca_certificates is passed on if you actually set it.
> Added two missing SSL config options to pass on to bunny

- lib/hutch/acknowledgements/nack_on_all_failures.rb
- lib/hutch/config.rb
- lib/hutch/worker.rb
- spec/hutch/worker_spec.rb
Code related to https://github.com/gocardless/hutch/issues/165
By default a nack is always sent on an exception.
Allows configuring custom handlers similar to the way logging is configured:
``` ruby
class Requeue
def handle(delivery_info, properties, broker, e)
if e.is_a?(Net::HTTPRetriableError) && !delivery_info.redelivered
broker.requeue delivery_info.delivery_tag
true
else
false
end
end
end
Hutch::Config.set :error_acknowledgements, [
Requeue.new
]
```
> Customizable error response handling (custom nacks)

- lib/hutch/broker.rb
According to bunny's connection document[0], Bunny#new accepts :logger parameter rather than :client_logger.
[0] http://rubybunny.info/articles/connecting.html
> bunny accepts logger parameter

- lib/hutch/worker.rb
- this local was used by an earlier `ensure` call, now gone
Credit: @jesjos
> Worker: Drop unused local, simpler rescue

- lib/hutch/cli.rb
It throws following error in my non rails app.
```ruby 
ruby-2.3.0/gems/hutch-0.20.0/lib/hutch/cli.rb:74:in `load_rails_app': uninitialized constant Rails (NameError)
```
There is config/environment.rb file in my app and it assumes that app is Rails app. But thats not the case. So I have adjusted the rails app detection logic and its working in my test env for both rails/non rails apps.  Any suggestions on using config/environment.rb file?
> Check existence of rails file to detect Rails app

- lib/hutch/cli.rb
I encountered problems in my consumer (failing to `bundle exec`) and found them hard to debug without output.
> Print load error exception in hutch executable

- lib/hutch/exceptions.rb
I could load Hutch on JRuby because it tries to load exceptions from Bunny regardless of which platform it's running on. 
This PR supports March Hare exceptions the same way that Bunny exceptions are handled for MRI.
> Re-enable JRuby support by requiring exception classes based on platform

- lib/hutch/worker.rb
This may be a matter of personal preference, but I think defaulting to DEBUG makes much more sense
> Log message using level DEBUG instead of INFO

- lib/hutch/broker.rb
- spec/hutch/broker_spec.rb
If the Hutch::Broker is changed like this, one could easily modify it in a way that will resolve #191 e.g.
``` ruby
class CustomBroker < Hutch::Broker
def exchange
return Thread.current[:exchange] if Thread.current[:exchange] 
declare_exchange!
end
def declare_exchange!(ch = open_channel)
Thread.current[:exchange] = declare_exchange(ch)
end
def disconnect
Thread.list.each { |t| t[:exchange] = nil if t[:exchange] }
super
end
end
def Hutch.connect(options = {}, config = Hutch::Config)
unless connected?
@broker = CustomBroker.new(config)
@broker.connect(options)
end
end
```
follow-up of #194 
see issue #191
> Versatile broker

- lib/hutch/cli.rb
- spec/hutch/cli_spec.rb
- Consolidates some code in the CLI around aborting when
required files don't exist
- Tests the messaging when CLI encounters SystemExit
> Addresses some code duplication and tightens up tests in Hutch::CLI

- lib/hutch/broker.rb
- lib/hutch/publisher.rb
- spec/hutch/broker_spec.rb
- Brings in `Hutch::Publisher` to do the publishing work for `Hutch::Broker`.
- Refactors methods specific to publishing to the new `Hutch::Publisher` class.
I believe these changes will be backwards compatible.
> Carves out a new Hutch::Publisher from Hutch::Broker

- lib/hutch/config.rb
- spec/hutch/broker_spec.rb
- spec/spec_helper.rb
Set client_logger in broker_spec to log to /dev/null.
I also got rid of deep_copy. The config should just be the default,
which means a call to Hutch::Logger.initialize will suffice.
Finally, I made the expected error in broker_spec more specific.
> Silence Bunny Logger in tests

- .gitignore
- .yardopts
- lib/hutch/worker.rb
This PR introduces config for [Yardoc](http://yardoc.org/), a system to render API docs.
- ignore rendered output `doc/` folder (we can publish it just after we render it)
- decide to use Markdown to style comments
- avoid a yardoc warning by expanding something that looked like an internal link to it
**Update**: Since Open Source is amazing, the YARD output is already automatically rendered by http://www.rubydoc.info/gems/hutch - so we can merely author prettier docs for it.
> WIP: YARD settings, docs

- .yardopts
- README.md
- Rakefile
- hutch.gemspec
- lib/hutch.rb
- lib/hutch/broker.rb
- lib/hutch/config.rb
- lib/yard-settings/handler.rb
- lib/yard-settings/legacy.rb
- lib/yard-settings/yard-settings.rb
- templates/default/class/setup.rb
- templates/default/fulldoc/html/css/hutch.css
- templates/default/layout/html/settings.erb
- templates/default/layout/html/setup.rb
- templates/default/method_details/html/settings.erb
- templates/default/method_details/setup.rb
- templates/default/module/html/settings.erb
- templates/default/module/setup.rb
In order to help users configure Hutch, try to tell the configuration story using YARD docs. This PR now produces docs.
Using a YARD processor, the names, types and default values can be presented in the documentation:
(Using the power of a CSS class, we could style that to be legible.)
> Docs: Hutch::Config

- Gemfile
- lib/hutch/config.rb
- spec/hutch/config_spec.rb
- spec/hutch/worker_spec.rb
- spec/spec_helper.rb
RSpec allows you to validate that mocked methods exist on classes, so I thought I would turn it on and fix what popped up.
> Validate partial doubles

- lib/hutch/cli.rb
- lib/hutch/config.rb
Adds white-space and tries to make the wording in settings documentation
more uniform.
Also: fixes #211, by logging-and-ignoring the `--daemonise` option on JRuby.
> Ignore daemonise on JRuby; docs 

- lib/yard-settings/handler.rb
- templates/default/module/html/settings.erb
[YARD can resolve internal links](http://www.rubydoc.info/gems/yard/0.8.7.2/YARD/Templates/Helpers/HtmlHelper#resolve_links-instance_method), and this brings prettier and more navigable settings documentation.
> Docs: HTML anchor links to settings methods

- lib/hutch/error_handlers/sentry.rb
- spec/hutch/error_handlers/sentry_spec.rb
When debugging errors in Hutch consumers, it's useful to be able to see the problematic message payload.  The error handlers for Airbrake and Honeybadger both send the payload as part of the notification, but the Sentry error handler does not.
This PR adds the payload in the `extra` information for Sentry, meaning that it'll show up alongside the error.
> Send payload in Sentry error handler

- lib/hutch/config.rb
- spec/hutch/config_spec.rb
This PR introduces a change which avoids throwing errors like "No config setting 'mq_host' exists" when the user gave a String instead of a Symbol.
> Config: .set and .get work with Strings, Symbols

- lib/hutch/worker.rb
In #236 it became clear to me that this other same-name constant `SHUTDOWN_SIGNALS` was not seeing any use in Worker. (Waiter has the right one.)
This PR removes it.
> Worker: Remove unused constant

- hutch.gemspec
- lib/hutch/error_handlers/airbrake.rb
- lib/hutch/error_handlers/honeybadger.rb
- lib/hutch/error_handlers/logger.rb
- lib/hutch/error_handlers/sentry.rb
- lib/hutch/worker.rb
- spec/hutch/error_handlers/airbrake_spec.rb
- spec/hutch/error_handlers/honeybadger_spec.rb
- spec/hutch/error_handlers/logger_spec.rb
- spec/hutch/error_handlers/sentry_spec.rb
Message properties can include valuable message informations such as
correlation id, message type, app specific headers and many more.
When handling consumer process errors, we should be able to make decisions
based on any message properties.
Note: This is a breaking change in case people created their own error handlers.
> Allows to pass all message properties to error handlers.

- lib/hutch/broker.rb
- lib/hutch/config.rb
- spec/hutch/broker_spec.rb
- spec/hutch/config_spec.rb
Config.initialize can be run again and again, not losing settings.
Question: That unprotected `@config.merge!(params)` - should it go via existing setters?
See #233
> Config: Defaults and ENV-loaded values stay

- hutch.gemspec
💁  The dependencies of this gem require a modern version of Ruby (see the following stderr output).
Specifying the required Ruby version in the configuration should help consumers using deprecated Rubies by failing fast during `gem install`, rather than during `bundle install`.
```
Gem::InstallError: amq-protocol requires Ruby version >= 2.0.
Gem::InstallError: mime-types-data requires Ruby version >= 2.0.
Gem::InstallError: tins requires Ruby version >= 2.0.
```
> Set required Ruby version

- hutch.gemspec
In order to use latest Rails, allow >= 4.0 of activesupport on Ruby versions larger than 2.3.
> Depend on activesupport >= 4.0 on Ruby versions greater than 2.3

- .rspec
- .travis.yml
- Gemfile
- hutch.gemspec
- lib/hutch/error_handlers/airbrake.rb
- spec/hutch/error_handlers/airbrake_spec.rb
- spec/hutch/waiter_spec.rb
On jruby-9k, we always fail on installing a development dependency which is used to generate documentation. Illustration: [Example failure to build](https://travis-ci.org/gocardless/hutch/jobs/161669440)
This PR improves things for JRuby:
- uses Kramdown for Markdown on JRuby
- skips using the QUIT signal in the tests, on the JRuby platform
- configures `JRUBY_OPTS=--debug` in builds
- removes JRuby from Travis' allowed_failures
- relies on latest published JRuby: jruby-9.1.5.0
- [has a fine explanation/theory on what could have caused a weird stacktrace](https://logs.jruby.org/jruby/2016-09-21)
- (and as a bonus round) upgrades the Airbrake error handler to its modern form (5.x)
Result:
- Travis builds on JRuby pass, and can publish test coverage data.
> Better support for JRuby in Travis, tests, gemspec

- CHANGELOG.md
- Gemfile
- lib/hutch/error_handlers.rb
- lib/hutch/error_handlers/opbeat.rb
- spec/hutch/error_handlers/opbeat_spec.rb
This PR adds an [Opbeat](https://github.com/opbeat/opbeat-ruby) error handler.
It needs trying out in my setting, but I'm using both Hutch and Opbeat, so it should be possible soon.
> Add an Opbeat error handler

- hutch.gemspec
This PR updates the multi_json gem in the gemspec.
- [CHANGELOG](https://github.com/intridea/multi_json/blob/master/CHANGELOG.md)
> Bump gem multi_json 1.12.1

- Gemfile
This PR wants to fix master so that [guard](https://github.com/guard/guard) and guard-rspec do not disturb other Travis build targets
> Gemfile: guard and guard-rspec work only on mri_23

- .gitignore
- .travis.yml
- Gemfile
- gemfiles/Gemfile.activesupport4
- gemfiles/Gemfile.activesupport5
- hutch.gemspec
This PR moves the development dependencies out of the gemspec and into groups in the Gemfile.
It also moves the version-dependent activesupport dependency into separated Gemfiles, so that the Travis build matrix targets can choose which activesupport version is for them.
By trying to leverage Bundler's `platform` support, we can get away from weird hacks in the gemspec.
In the Travis build matrix each Ruby version gets its dependencies pointed out to it using the `gemfile:` travis.yml feature. A `gemfiles/` folder is supplied.
> Gemspec: Move development deps to Gemfile

- README.md
Environment based configuration is possible in `Hutch` but this was only apparent if someone took a look into `lib/hutch/config.rb`.
This changeset updates the readme to mention the possibility of this and also provides a cheat sheet for the configuration preference order.
Easier to view changes: https://github.com/sldblog/hutch/blob/dl-update-configuration-readme/README.md#environment-variables
> Extend readme with environment based configuration

- lib/hutch/error_handlers/opbeat.rb
This PR makes a trivial change to how error message strings are formatted: favoring string interpolation over `+` concatenation.
> Opbeat ErrorHandler: string interpolation

- lib/hutch/error_handlers/airbrake.rb
- lib/hutch/error_handlers/honeybadger.rb
- lib/hutch/error_handlers/logger.rb
- lib/hutch/error_handlers/sentry.rb
Trivial change to string interpolation in log messages in error handlers.
This is a follow-up PR to a previous change to the Opbeat error handler. See #257
> Style: prefer string interpolation, not concat

- README.md
See #223 
This PR adds the YARD-generated Config section into the README.
This adds a manual step for maintenance.
Issues I want feedback on:
- Some of the options available to the Hutch::Config-using public are not primitive values, and they're not represented in this generated table. The list of settings that already exists in the README introduces some of the others. Is that list complete?
- Updating this took me running `yard` and then stripping `<a>` tags from the names of configuration options.
> README.md: Add generated Config docs section

- lib/hutch/tracers.rb
- lib/hutch/tracers/opbeat.rb
- spec/tracers/opbeat_spec.rb
This PR adds a new autoloaded Tracer implementation for Opbeat.
> Add an Opbeat Tracer

- lib/hutch/logging.rb
The last statement of the Config class is to run initialize. We don't need to do it twice.
> Logging: remove redundant Hutch::Config.initialize

- .travis.yml
- Gemfile
- Rakefile
- gemfiles/Gemfile.activesupport4
- gemfiles/Gemfile.activesupport5
- hutch.gemspec
This PR changes the Gemfile for the project, to include the Bundler feature [`ruby RUBY_VERSION`](https://bundler.io/v1.13/man/gemfile.5.html#RUBY), so that Bundler can locate the right gems for the current Ruby version.
Current status: ~experimental~ This passes all Travis tests, and does the right thing.
- hutch.gemspec: Avoid concatenating a String by using line-continuation operator instead.
> Gemfile with ruby version marker, instead of specific gemfiles/ files

- lib/hutch/waiter.rb
- spec/hutch/waiter_spec.rb
This is a PR inspired by another project which had a neat section of signals to send to the worker, to have to do things, like "shed current work item, never to requeue it" or "print a debug backtrace".
- [Kuryuk - Signals chapter of docs](http://kuyruk.readthedocs.io/en/latest/signals.html)
- [Mike Perham's Sidekiq's wiki on Signals](https://github.com/mperham/sidekiq/wiki/Signals)
- What signals should the Worker process handle?
- Can you golf the control structure exception away? (See - this is me feeling safe enough here to publish some not-so-great code.)
- introduce a USR2 signal to print all the Threads' backtraces
- generally keep the signals uppercased
> Perform a VM-wide thread stack trace dump on USR2

- README.md
I want the README to stay easy to use, even as we add more to it.
I propose we add a Table of Contents, using some tool to keep it updated.
What do you say?
- ToC
- Shorter headings
- more focused sections
> README ToC: add one

- README.md
- lib/hutch/config.rb
- lib/hutch/worker.rb
- spec/hutch/worker_spec.rb
Allows us to configure the consumer names (tags) that are visible in RabbitMQ.
Tagging with specific names is useful for us because we have over 100 queues and lots of applications communicating. If we aim to be easily identifiable, we can do these things:
- define a routing key convention that refers to the application publishing the message
- define a queue name convention that identifies the consumers
- identify consumers by tag names
Out of the above three we cannot do the last one. So this changeset enables that configuration :)
The default tag name changes from `bunny` to `hutch` with this change.
Explains on how to (still manually) update the generated configuration section in the readme.
> Configure consumer tag names/prefixes

- README.md
- lib/hutch/config.rb
Note, I see in the logs that this shouldn't be used from the CLI, but I see that the CLI class is manually processing it's options so this work happen as a result of this.
Also updates the readme to show the URI option (via yard generation).
Fixes #269.
> Expose uri as normal config setting, so it can be used in ENV

- .travis.yml
- lib/hutch/waiter.rb
- spec/hutch/waiter_spec.rb
This PR
- adds 2.4.0 to the build matrix
- updates to latest JRuby
> Travis: Add 2.4.0, use jruby-9.1.7.0; don't trap QUIT on JRuby since it's not supported

- .travis.yml
While investigating if it would be possible to remove the `ruby RUBY_VERSION` marker in the Gemfile, I noted that we don't upgrade Rubygems before using it.
Do we want to?
> Travis: Rubygems update in before_install

- lib/hutch/error_handlers/honeybadger.rb
- spec/hutch/error_handlers/honeybadger_spec.rb
The API method used is [removed in the upstream 3.0.0](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/CHANGELOG.md#300---2017-02-06), which was just released (two, three weeks ago).
I read [the new method's docs](http://www.rubydoc.info/gems/honeybadger/Honeybadger%3Anotify) again, and noted that if the first arg is a Hash, then it's just 1 argument.
> Wrap API of error handler for Honeybadger

- README.md
This PR adds contextual notes to the Example section on x-max-length.
> README: Improve RabbitMQ docs links

- README.md
Just a quick fix while reading your docs
> Fix a link to topic exchange docs in readme

- lib/hutch/cli.rb
Add rails environment log information to Hutch::CLI.
When use `bundle exec hutch -v` to run hutch there is no exactly information about what is the rails environment is use.
> when boot rails project, log rails environment

- lib/hutch/waiter.rb
This PR fixes a very small detail: the YARD directive for "this raises an exception".
I used the yard-junk gem to find it. It worked.
> [docs] Fix YARD annotation

- lib/hutch/error_handlers/honeybadger.rb
#274 wraps the Honeybadger API to use `notify` after the removal of `notify_or_ignore`. By default, `notify` behaves the same, ignoring notices based on configuration. With the `force` option set to `true`, this is changed to notify regardless of whether the notice was configured to be ignored.
Hence, I'm removing the `force` option to restore previous behaviour.
> Honey badger notify no force

- .travis.yml
This tiny PR removes a step which `rvm` now performs on its on.
> Travis: rvm nowadays self-updates "gem"

- .travis.yml
This PR uses ruby 2.4.2, 2.3.5, 2.2.8 in the build matrix, as soon as `rvm` supports it.
> Travis: Update Rubies in matrix

- lib/hutch/cli.rb
- lib/hutch/config.rb
- lib/hutch/worker.rb
In case you use hutch with rails and you no need to run all consumers. Or if you need to split then into groups to balance load. Then define groups in config file:
``` yml
consumers_groups:
payments:
- DepositConsumer
- CashoutConsumer
notification:
- EmailNotificationConsumer
```
and run ``` hutch --only-group=payments --config=CONFIG_PATH```
> Group consumers

- .travis.yml
This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/12/07/jruby-9-1-15-0.html
> Travis: use latest jruby

- lib/hutch/cli.rb
- lib/hutch/error_handlers/airbrake.rb
- lib/hutch/error_handlers/honeybadger.rb
- lib/hutch/error_handlers/logger.rb
- lib/hutch/error_handlers/opbeat.rb
- lib/hutch/error_handlers/sentry.rb
- spec/hutch/error_handlers/airbrake_spec.rb
- spec/hutch/error_handlers/honeybadger_spec.rb
- spec/hutch/error_handlers/logger_spec.rb
- spec/hutch/error_handlers/opbeat_spec.rb
- spec/hutch/error_handlers/sentry_spec.rb
To handle setup exceptions, a method was added to each error handler.
Said method is subsequently called when setup of the client fails.
This is to ensure that a failed setup is not only logged, but also
reported to e.g. sentry.
Closes #288
> Handle setup exceptions

- lib/hutch/cli.rb
- lib/hutch/error_handlers/airbrake.rb
- lib/hutch/error_handlers/base.rb
- lib/hutch/error_handlers/honeybadger.rb
- lib/hutch/error_handlers/logger.rb
- lib/hutch/error_handlers/opbeat.rb
- lib/hutch/error_handlers/sentry.rb
- spec/hutch/cli_spec.rb
- spec/hutch/error_handlers/airbrake_spec.rb
- spec/hutch/error_handlers/honeybadger_spec.rb
- spec/hutch/error_handlers/logger_spec.rb
- spec/hutch/error_handlers/opbeat_spec.rb
- spec/hutch/error_handlers/sentry_spec.rb
To handle setup exceptions, a method was added to each error handler.
Said method is subsequently called when setup of the client fails.
This is to ensure that a failed setup is not only logged, but also
reported to e.g. sentry.
Furthermore, a base class indicating the interface for error handlers is added.
Closes #288
> Add error handler class

- lib/hutch/broker.rb
- spec/hutch/broker_spec.rb
Restores functionality implemented in https://github.com/gocardless/hutch/pull/159 and since lost to:
* Respect `amqps` specification when using the URI config option (ie. utilise TLS)
* Default to the standard protocol ports when not specified and using the URI config option (5671 for TLS, 5672 otherwise)
This means that:
`amqp://guest:guest@127.0.0.1/` connects to the server on port 5672 and does not utilise TLS.
`amqps://guest:guest@127.0.0.1/` connects to the server on port 5671 and does utilise TLS.
It also adds test cases for this functionality to prevent another regression.
Changes are all within `Hutch::Broker#parse_uri`
Background context can be found in the original issue ://github.com/gocardless/hutch/issues/304
The test for covering when amqps scheme is utilised has to stub …
> When using the uri config option: Respect amqps specification and use default protocol ports if unspecified

- README.md
This small change is to emphasise that whilst the majority of the work was completed at GC, it's now a community project since we don't actively use it at GC 🎉
> Mention GoCardless origin but remove "join us" footer

- CHANGELOG.md
This adds a changelog entry for v0.25.0, detailing all of the commits [since v0.24.0](https://github.com/gocardless/hutch/compare/v0.24.0...v0.25.0) which bring user-facing changes (e.g. not dependency bumps or test changes).
> Add changelog entry for v0.25.0

- lib/hutch.rb
When there are competing publisher threads, there is a chance that the
publisher has not been initialized when Hutch is registered as
connected.  This happens when connections are lazily created vs at application load (for example).
The following diagram should shed some light on the race condition:
```
Thread 1                  Hutch                   Thread 2
--------                  -------                 ---------
t1      Hutch.publish()  --->  connected? (FALSE)
|-> open_connection!
t2                             connected? (TRUE)  <--- Hutch.publish()
@broker.publish()   |-> NoMethodError (@publisher)
t3                         |-> declare_publisher!
PUBLISHED        <-|   @broker.publish()
```
Wrapping the `Hutch.connect` call should resolve this issue.
> Ensure that connecting method is synchronized

- lib/hutch/worker.rb
It seems during rename(https://github.com/gocardless/hutch/commit/d509c19763902e6ebf07a57d78a24431f254015c#diff-16eb6365e2d1f19f4df2b8aba16e4f9cL121) took place a mistake.
> Fix NameError: undefined local variable or method `allowed_consumers`

- .travis.yml
This PR updates the CI matrix to use latest JRuby, 9.2.5.0.
Also, adds Ruby 2.6.0.
[JRuby 9.2.5.0 release blog post](https://www.jruby.org/2018/12/06/jruby-9-2-5-0.html)
> Travis: update to latest JRuby, Ruby

- .travis.yml
This PR updates the CI matrix to use latest JRuby, 9.2.6.0.
[JRuby 9.2.6.0 release blog post](https://www.jruby.org/2019/02/11/jruby-9-2-6-0.html)
> CI: update matrix - new JRuby out

- .travis.yml
This PR updates the CI matrix to the latest release.
> CI: Use 2.5.5, 2.6.2

- spec/hutch/waiter_spec.rb
In a discussion on what the 9.2.6.0 JRuby RSpec test failure meant, the tests about TERM and INT signals were mentioned.
This PR disables those tests, temporarily, for JRuby.
> Ignore Signal tests unsupported on JRuby

- lib/hutch/broker.rb
- lib/hutch/publisher.rb
Having the entire payload logged at the "INFO" level is not ideal due to
the following reasons:
- PII data might be contained there and there is no way to fitler it out
- Payload might be big enough that logging aggregators might struggle with
the sheer amount of data
- Since the log level is shared by reusing the rails/sinatra logger, INFO level
might be too verbose for hutch but WARN level not verbose enough for the other.
While initially I considered implementing a feature to allow for filtering
the payload for PII or triming the output, a quick solution to all problems
listed above is to split the logging into two, the INFO level handing the
generic part of the log, with the message ID injected for easy tracking
and in case the payload is needed, log level can be set to DEBUG, which …
> Better log levels in the message publisher

- README.md
Dir.glob(File.join('**', '*_consumer.rb')) will load gem bunny guide class, result in rails startup failure.
> Update README.md change autoloads

- lib/hutch/broker.rb
- lib/hutch/config.rb
This changes makes the exchange type configurable with a default to use a topic exchange. 
This is done simply by declaring the exchange through a different Bunny API:
not using the `channel.topic()` shortcut but initializing a new `Bunny::Exchange.new()` 
Though Hutch is opinionated on the exchange/message types used. (which is good!) this makes it possible to for example use Hutch in combination with the [delayed message exchange RabbitMQ plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) which defines a new exchange type but can act like a topic exchange.
Example usage:
```
Hutch::Config.set(:mq_exchange_type, 'x-delayed-message')
Hutch::Config.set(:mq_exchange_options, { arguments: { 'x-delayed-type': 'topic' } })
```
I don't know much about RabbitMQ internals and …
> Make RabbitMQ exchange type configurable

- CHANGELOG.md
Minor edit to add missing `mq_exchange_type` to the changelog.
> Updated changelog for mq_exchange_type

- README.md
- lib/hutch/config.rb
- lib/hutch/serializers/json.rb
Hi,
I've made a PR for two distinct reasons (hence the two commits!)
**Add namespace to the readme** 08c8eaf
It seems like a pretty valid config, let's expose it!
**enforce MultiJson usage** 6cfb105
This allows users to always have their chosen implementation used. And gives a more consistent behavior.
Thanks for the great tool 🚀
> Add namespace to documentation + Enforce `MultiJson` usage

- Gemfile
- README.md
- lib/hutch/tracers.rb
- lib/hutch/tracers/datadog.rb
- spec/hutch/tracers/datadog_spec.rb
There is already a tracer for NewRelic. Having a tracer for Datadog as well sounds like a good idea then.
> add Datadog tracer

- .travis.yml
This PR updates the CI matrix to use latest JRuby, **9.2.16.0**.
[JRuby 9.2.16.0 release blog post](https://www.jruby.org/2021/03/03/jruby-9-2-16-0.html)
> CI: Use latest 9.2 JRuby

- lib/hutch/config.rb
- spec/hutch/config_spec.rb
I had a pretty unfortunate issue when directly setting the config value for `heartbeat` without an explicit typecasting: `Hutch::Config.set(:heartbeat, ENV.fetch("HUTCH_HEARTBEAT", 30))` but the ENV var was obviously a string and it caused some failures when publishing messages. Since the type is explicitly declared on a config level, I believe the desired behaviour would be to handle type-casting inside `set` method as well.
> handle type-casting for config, even when explicitly setting values using .set method

- Gemfile
- lib/hutch/cli.rb
- lib/hutch/error_handlers.rb
- lib/hutch/error_handlers/sentry_raven.rb
- spec/hutch/error_handlers/sentry_raven_spec.rb
Turns out that Sentry as Raven is deprecated and is going to be replaced by literal Sentry, coming from `sentry-ruby` SDK. So I renamed the existing error handler to SentryRaven and added a new Sentry one.
> add 'literal' Sentry error handler and make it separate from legacy Raven

- .travis.yml
Try using a named entry to be able to easier match it.
This PR updates the CI matrix to use latest JRuby, **9.2.19.0**.
[JRuby 9.2.19.0 release blog post](https://www.jruby.org/2021/06/15/jruby-9-2-19-0.html)
> CI: Configure JRuby 9.2.19.0

- lib/hutch/broker.rb
- lib/hutch/consumer.rb
- lib/hutch/worker.rb
- spec/hutch/broker_spec.rb
- spec/hutch/worker_spec.rb
want to make use of bunny queue options, e.g. disallow application to create queue by setting `no_declare: true`
> Make Bunny all queue options available

- lib/hutch/config.rb
- spec/hutch/config_spec.rb
This fixes a warning raised by Ruby 2.7 when attempting to check a
boolean against a regexp:
.../lib/hutch/config.rb:225: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
> Fix warning about usage of TrueClass#=~ on Ruby 2.7

- lib/hutch/cli.rb
Fixes a bug with requiring components.
Example: https://github.com/AlexanderMint/hutch_example_error
If an executable file has paths added to $LOAD_PATH, then the last path added by the user will be removed
> Fix $LOAD_PATH error

- lib/hutch/broker.rb
- spec/hutch/broker_spec.rb
I regularly include the magic comment, `# frozen_string_literal: true`, in my ruby code.
This results in an error when defining a `queue_name` in a consumer class, since the `Hutch::Broker` class will modify the string instead of creating a new one: `lib/hutch/broker.rb:177:in 'prepend': can't modify frozen String (FrozenError)`
> Do not modify queue name in place. Create a new String

- lib/hutch/consumer.rb
- lib/hutch/worker.rb
- spec/hutch/worker_spec.rb
Fix Issue in (requeue! and reject! )
For Example:
When you are using reject!
1. Will broker.reject(delivery_info.delivery_tag) -> will go to def reject in broker.rb
2. Will call channel.reject(delivery_tag, false)-> will go to bunny reject in channel.rb
3. Will call  basic_reject(delivery_tag.to_i, false) which going to reject the message So it's acknowledged
4. In worker.rb handle_message by default do  @broker.ack(delivery_info.delivery_tag) so it's going to be double acknowledged
Solution : 
1. Add Boolean in reject and requeue in broker.rb that message rejected
2. in handle_message before doing default ack check on this boolean
> fix: reject and requeue double acknowledgement

- lib/hutch/broker.rb
- lib/hutch/config.rb
Exposes the ability to configure Bunny's `auth_mechanism` parameter, so that TLS certificate authentication may be used.
See http://rubybunny.info/articles/connecting.html for details.
> Allow auth mechanism to be configured

- lib/hutch/worker.rb
When handling an error, it would be useful to know the delivery_info such as the routing key. This adds delivery_info to message properties. This seemed the only way to supply the information without changing the error handler contract.
> Add delivery_info to properties for error handler

- README.md
- lib/hutch/broker.rb
- lib/hutch/config.rb
Thank you for this project! :heart:
I've noticed an opportunity to enhance observability from the broker's perspective.
Firstly, introducing a feature to set a human-friendly connection name would greatly improve the ability to distinguish connections easily.
Secondly, providing additional information in client properties could be useful in identifying issues with applications, such as the application version.
With this pull request, I propose adding two additional configuration options:
1. `connection_name` - to set the connection name conveniently. It can be easily controlled with the `HUTCH_CONNECTION_NAME` environment variable, requiring no explicit configuration.   
2. `mq_client_properties` - to manage all client properties, including the `connection_name`.
```ruby
Hutch::Config.set …
```
> Client properties

- lib/hutch/broker.rb
`OpenStruct` is optional since `JSON` v 2.7.2
References:
- https://github.com/flori/json/pull/565
- https://github.com/ruby/ostruct/blob/master/lib/ostruct.rb#L136
This commit fixes error:
```
Hutch.connect
gems/hutch-1.2.0/lib/hutch/broker.rb:272:in `api_config': uninitialized constant Hutch::Broker::OpenStruct (NameError)
@api_config ||= OpenStruct.new.tap do |config|
^^^^^^^^^^
```
> Require ostruct explicitly

- .github/workflows/test.yml
The numeric version `3.0` is treated as `3`. As result, the latest Ruby 3.x version is used for testing instead of Ruby 3.0.
Using the text notation `'3.0'` makes Github Action to use the proper version for testing (Ruby 3.0)
> Take the minor version of Ruby into account

- hutch.gemspec
With the release of Rails 8.0.0.1 the dependency update I made as part of https://github.com/ruby-amqp/hutch/pull/402 is too strict and the gem gets downgraded to version 0.23.1 as part of a rails upgrade
It might be better to remove the upper ceiling on `activesupport` so this doesn't become a recurring blocker for future rails releases
> Remove upper dependency version limit on activesupport

- hutch.gemspec
- lib/hutch/version.rb
- spec/spec_helper.rb
Addresses the following raised issue: 
- https://github.com/ruby-amqp/hutch/issues/406
ostruct is being removed as a default gem from Ruby 3.5+, see also:
- https://github.com/ruby/ruby/pull/10428
- https://github.com/rails/jbuilder/issues/561
- https://github.com/mileszs/wicked_pdf/issues/1116
> Make `ostruct` an explicit dependency

- lib/hutch/tracers/datadog.rb
From https://rubygems.org/gems/ddtrace
> NOTICE: This gem has been renamed to `datadog` since 2.0.0. Please use `datadog` instead of `ddtrace`. ddtrace is Datadog's tracing client for Ruby. It is used to trace requests as they flow across web servers, databases and microservices so that developers have great visiblity into bottlenecks and troublesome requests.
Add support for the new `datadog` gem.
> Add compatibility for ddtrace and datadog gems

- hutch.gemspec
- lib/hutch/broker.rb
- spec/hutch/error_handlers/airbrake_spec.rb
- spec/hutch/error_handlers/bugsnag_spec.rb
- spec/hutch/error_handlers/honeybadger_spec.rb
- spec/hutch/error_handlers/logger_spec.rb
- spec/hutch/error_handlers/rollbar_spec.rb
- spec/hutch/error_handlers/sentry_raven_spec.rb
- spec/hutch/error_handlers/sentry_spec.rb
- spec/hutch/tracers/datadog_spec.rb
- spec/spec_helper.rb
The only usage in library code was to hold the config and that is never exposed to users. Just use a normal struct for that.
> Drop dependency on `ostruct`
